{% set name = "de-bundeshaushalt" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/de-bundeshaushalt-{{ version }}.tar.gz
  sha256: 249649132d5962678da9055ed2ccb5d3a6a683ea0133139a7f866991e9b3dd17

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - python-dateutil
    - urllib3 >=1.25.3

test:
  imports:
    - deutschland.bundeshaushalt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bundesAPI/&lt;REPO&gt;
  summary: Bundeshaushalt API
  license: Apache-2.0
  license_file: 
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
